/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.isy.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefenseRate implements Serializable {

    private static final long serialVersionUID = 904577585;

    private String defenseOrderId;
    private String graduationDesignTeacherId;
    private Double grade;

    public DefenseRate() {}

    public DefenseRate(DefenseRate value) {
        this.defenseOrderId = value.defenseOrderId;
        this.graduationDesignTeacherId = value.graduationDesignTeacherId;
        this.grade = value.grade;
    }

    public DefenseRate(
        String defenseOrderId,
        String graduationDesignTeacherId,
        Double grade
    ) {
        this.defenseOrderId = defenseOrderId;
        this.graduationDesignTeacherId = graduationDesignTeacherId;
        this.grade = grade;
    }

    @NotNull
    @Size(max = 64)
    public String getDefenseOrderId() {
        return this.defenseOrderId;
    }

    public void setDefenseOrderId(String defenseOrderId) {
        this.defenseOrderId = defenseOrderId;
    }

    @NotNull
    @Size(max = 64)
    public String getGraduationDesignTeacherId() {
        return this.graduationDesignTeacherId;
    }

    public void setGraduationDesignTeacherId(String graduationDesignTeacherId) {
        this.graduationDesignTeacherId = graduationDesignTeacherId;
    }

    @NotNull
    public Double getGrade() {
        return this.grade;
    }

    public void setGrade(Double grade) {
        this.grade = grade;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DefenseRate (");

        sb.append(defenseOrderId);
        sb.append(", ").append(graduationDesignTeacherId);
        sb.append(", ").append(grade);

        sb.append(")");
        return sb.toString();
    }
}
