/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.isy.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefenseTime implements Serializable {

    private static final long serialVersionUID = 791161545;

    private String  defenseStartTime;
    private String  defenseEndTime;
    private Integer sortTime;
    private String  defenseArrangementId;

    public DefenseTime() {}

    public DefenseTime(DefenseTime value) {
        this.defenseStartTime = value.defenseStartTime;
        this.defenseEndTime = value.defenseEndTime;
        this.sortTime = value.sortTime;
        this.defenseArrangementId = value.defenseArrangementId;
    }

    public DefenseTime(
        String  defenseStartTime,
        String  defenseEndTime,
        Integer sortTime,
        String  defenseArrangementId
    ) {
        this.defenseStartTime = defenseStartTime;
        this.defenseEndTime = defenseEndTime;
        this.sortTime = sortTime;
        this.defenseArrangementId = defenseArrangementId;
    }

    @NotNull
    @Size(max = 20)
    public String getDefenseStartTime() {
        return this.defenseStartTime;
    }

    public void setDefenseStartTime(String defenseStartTime) {
        this.defenseStartTime = defenseStartTime;
    }

    @NotNull
    @Size(max = 20)
    public String getDefenseEndTime() {
        return this.defenseEndTime;
    }

    public void setDefenseEndTime(String defenseEndTime) {
        this.defenseEndTime = defenseEndTime;
    }

    @NotNull
    public Integer getSortTime() {
        return this.sortTime;
    }

    public void setSortTime(Integer sortTime) {
        this.sortTime = sortTime;
    }

    @NotNull
    @Size(max = 64)
    public String getDefenseArrangementId() {
        return this.defenseArrangementId;
    }

    public void setDefenseArrangementId(String defenseArrangementId) {
        this.defenseArrangementId = defenseArrangementId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DefenseTime (");

        sb.append(defenseStartTime);
        sb.append(", ").append(defenseEndTime);
        sb.append(", ").append(sortTime);
        sb.append(", ").append(defenseArrangementId);

        sb.append(")");
        return sb.toString();
    }
}
