/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.isy.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GraduateArchives implements Serializable {

    private static final long serialVersionUID = 1448691113;

    private String graduateBillId;
    private Byte   isExcellent;
    private String archiveNumber;
    private String note;

    public GraduateArchives() {}

    public GraduateArchives(GraduateArchives value) {
        this.graduateBillId = value.graduateBillId;
        this.isExcellent = value.isExcellent;
        this.archiveNumber = value.archiveNumber;
        this.note = value.note;
    }

    public GraduateArchives(
        String graduateBillId,
        Byte   isExcellent,
        String archiveNumber,
        String note
    ) {
        this.graduateBillId = graduateBillId;
        this.isExcellent = isExcellent;
        this.archiveNumber = archiveNumber;
        this.note = note;
    }

    @NotNull
    @Size(max = 64)
    public String getGraduateBillId() {
        return this.graduateBillId;
    }

    public void setGraduateBillId(String graduateBillId) {
        this.graduateBillId = graduateBillId;
    }

    public Byte getIsExcellent() {
        return this.isExcellent;
    }

    public void setIsExcellent(Byte isExcellent) {
        this.isExcellent = isExcellent;
    }

    @NotNull
    @Size(max = 100)
    public String getArchiveNumber() {
        return this.archiveNumber;
    }

    public void setArchiveNumber(String archiveNumber) {
        this.archiveNumber = archiveNumber;
    }

    @Size(max = 100)
    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GraduateArchives (");

        sb.append(graduateBillId);
        sb.append(", ").append(isExcellent);
        sb.append(", ").append(archiveNumber);
        sb.append(", ").append(note);

        sb.append(")");
        return sb.toString();
    }
}
