/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.isy.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GraduationDesignDatumGroup implements Serializable {

    private static final long serialVersionUID = -1141461749;

    private String graduationDesignDatumGroupId;
    private String fileId;
    private String graduationDesignTeacherId;

    public GraduationDesignDatumGroup() {}

    public GraduationDesignDatumGroup(GraduationDesignDatumGroup value) {
        this.graduationDesignDatumGroupId = value.graduationDesignDatumGroupId;
        this.fileId = value.fileId;
        this.graduationDesignTeacherId = value.graduationDesignTeacherId;
    }

    public GraduationDesignDatumGroup(
        String graduationDesignDatumGroupId,
        String fileId,
        String graduationDesignTeacherId
    ) {
        this.graduationDesignDatumGroupId = graduationDesignDatumGroupId;
        this.fileId = fileId;
        this.graduationDesignTeacherId = graduationDesignTeacherId;
    }

    @NotNull
    @Size(max = 64)
    public String getGraduationDesignDatumGroupId() {
        return this.graduationDesignDatumGroupId;
    }

    public void setGraduationDesignDatumGroupId(String graduationDesignDatumGroupId) {
        this.graduationDesignDatumGroupId = graduationDesignDatumGroupId;
    }

    @NotNull
    @Size(max = 64)
    public String getFileId() {
        return this.fileId;
    }

    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    @NotNull
    @Size(max = 64)
    public String getGraduationDesignTeacherId() {
        return this.graduationDesignTeacherId;
    }

    public void setGraduationDesignTeacherId(String graduationDesignTeacherId) {
        this.graduationDesignTeacherId = graduationDesignTeacherId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GraduationDesignDatumGroup (");

        sb.append(graduationDesignDatumGroupId);
        sb.append(", ").append(fileId);
        sb.append(", ").append(graduationDesignTeacherId);

        sb.append(")");
        return sb.toString();
    }
}
