/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.isy.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GraduationDesignRelease implements Serializable {

    private static final long serialVersionUID = 3727311;

    private String    graduationDesignReleaseId;
    private String    graduationDesignTitle;
    private Timestamp releaseTime;
    private String    username;
    private Timestamp startTime;
    private Timestamp endTime;
    private Timestamp fillTeacherStartTime;
    private Timestamp fillTeacherEndTime;
    private Byte      graduationDesignIsDel;
    private String    allowGrade;
    private Integer   departmentId;
    private Integer   scienceId;

    public GraduationDesignRelease() {}

    public GraduationDesignRelease(GraduationDesignRelease value) {
        this.graduationDesignReleaseId = value.graduationDesignReleaseId;
        this.graduationDesignTitle = value.graduationDesignTitle;
        this.releaseTime = value.releaseTime;
        this.username = value.username;
        this.startTime = value.startTime;
        this.endTime = value.endTime;
        this.fillTeacherStartTime = value.fillTeacherStartTime;
        this.fillTeacherEndTime = value.fillTeacherEndTime;
        this.graduationDesignIsDel = value.graduationDesignIsDel;
        this.allowGrade = value.allowGrade;
        this.departmentId = value.departmentId;
        this.scienceId = value.scienceId;
    }

    public GraduationDesignRelease(
        String    graduationDesignReleaseId,
        String    graduationDesignTitle,
        Timestamp releaseTime,
        String    username,
        Timestamp startTime,
        Timestamp endTime,
        Timestamp fillTeacherStartTime,
        Timestamp fillTeacherEndTime,
        Byte      graduationDesignIsDel,
        String    allowGrade,
        Integer   departmentId,
        Integer   scienceId
    ) {
        this.graduationDesignReleaseId = graduationDesignReleaseId;
        this.graduationDesignTitle = graduationDesignTitle;
        this.releaseTime = releaseTime;
        this.username = username;
        this.startTime = startTime;
        this.endTime = endTime;
        this.fillTeacherStartTime = fillTeacherStartTime;
        this.fillTeacherEndTime = fillTeacherEndTime;
        this.graduationDesignIsDel = graduationDesignIsDel;
        this.allowGrade = allowGrade;
        this.departmentId = departmentId;
        this.scienceId = scienceId;
    }

    @NotNull
    @Size(max = 64)
    public String getGraduationDesignReleaseId() {
        return this.graduationDesignReleaseId;
    }

    public void setGraduationDesignReleaseId(String graduationDesignReleaseId) {
        this.graduationDesignReleaseId = graduationDesignReleaseId;
    }

    @NotNull
    @Size(max = 100)
    public String getGraduationDesignTitle() {
        return this.graduationDesignTitle;
    }

    public void setGraduationDesignTitle(String graduationDesignTitle) {
        this.graduationDesignTitle = graduationDesignTitle;
    }

    public Timestamp getReleaseTime() {
        return this.releaseTime;
    }

    public void setReleaseTime(Timestamp releaseTime) {
        this.releaseTime = releaseTime;
    }

    @NotNull
    @Size(max = 64)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @NotNull
    public Timestamp getStartTime() {
        return this.startTime;
    }

    public void setStartTime(Timestamp startTime) {
        this.startTime = startTime;
    }

    @NotNull
    public Timestamp getEndTime() {
        return this.endTime;
    }

    public void setEndTime(Timestamp endTime) {
        this.endTime = endTime;
    }

    @NotNull
    public Timestamp getFillTeacherStartTime() {
        return this.fillTeacherStartTime;
    }

    public void setFillTeacherStartTime(Timestamp fillTeacherStartTime) {
        this.fillTeacherStartTime = fillTeacherStartTime;
    }

    @NotNull
    public Timestamp getFillTeacherEndTime() {
        return this.fillTeacherEndTime;
    }

    public void setFillTeacherEndTime(Timestamp fillTeacherEndTime) {
        this.fillTeacherEndTime = fillTeacherEndTime;
    }

    @NotNull
    public Byte getGraduationDesignIsDel() {
        return this.graduationDesignIsDel;
    }

    public void setGraduationDesignIsDel(Byte graduationDesignIsDel) {
        this.graduationDesignIsDel = graduationDesignIsDel;
    }

    @NotNull
    @Size(max = 5)
    public String getAllowGrade() {
        return this.allowGrade;
    }

    public void setAllowGrade(String allowGrade) {
        this.allowGrade = allowGrade;
    }

    @NotNull
    public Integer getDepartmentId() {
        return this.departmentId;
    }

    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    @NotNull
    public Integer getScienceId() {
        return this.scienceId;
    }

    public void setScienceId(Integer scienceId) {
        this.scienceId = scienceId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GraduationDesignRelease (");

        sb.append(graduationDesignReleaseId);
        sb.append(", ").append(graduationDesignTitle);
        sb.append(", ").append(releaseTime);
        sb.append(", ").append(username);
        sb.append(", ").append(startTime);
        sb.append(", ").append(endTime);
        sb.append(", ").append(fillTeacherStartTime);
        sb.append(", ").append(fillTeacherEndTime);
        sb.append(", ").append(graduationDesignIsDel);
        sb.append(", ").append(allowGrade);
        sb.append(", ").append(departmentId);
        sb.append(", ").append(scienceId);

        sb.append(")");
        return sb.toString();
    }
}
