/**
 * This class is generated by jOOQ
 */
package top.zbeboy.isy.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InternshipApply implements Serializable {

	private static final long serialVersionUID = 1296408356;

	private String    internshipApplyId;
	private Integer   studentId;
	private String    internshipReleaseId;
	private Integer   internshipApplyState;
	private Timestamp changeFillStartTime;
	private Timestamp changeFillEndTime;

	public InternshipApply() {}

	public InternshipApply(InternshipApply value) {
		this.internshipApplyId = value.internshipApplyId;
		this.studentId = value.studentId;
		this.internshipReleaseId = value.internshipReleaseId;
		this.internshipApplyState = value.internshipApplyState;
		this.changeFillStartTime = value.changeFillStartTime;
		this.changeFillEndTime = value.changeFillEndTime;
	}

	public InternshipApply(
		String    internshipApplyId,
		Integer   studentId,
		String    internshipReleaseId,
		Integer   internshipApplyState,
		Timestamp changeFillStartTime,
		Timestamp changeFillEndTime
	) {
		this.internshipApplyId = internshipApplyId;
		this.studentId = studentId;
		this.internshipReleaseId = internshipReleaseId;
		this.internshipApplyState = internshipApplyState;
		this.changeFillStartTime = changeFillStartTime;
		this.changeFillEndTime = changeFillEndTime;
	}

	@NotNull
	@Size(max = 100)
	public String getInternshipApplyId() {
		return this.internshipApplyId;
	}

	public void setInternshipApplyId(String internshipApplyId) {
		this.internshipApplyId = internshipApplyId;
	}

	@NotNull
	public Integer getStudentId() {
		return this.studentId;
	}

	public void setStudentId(Integer studentId) {
		this.studentId = studentId;
	}

	@NotNull
	@Size(max = 100)
	public String getInternshipReleaseId() {
		return this.internshipReleaseId;
	}

	public void setInternshipReleaseId(String internshipReleaseId) {
		this.internshipReleaseId = internshipReleaseId;
	}

	public Integer getInternshipApplyState() {
		return this.internshipApplyState;
	}

	public void setInternshipApplyState(Integer internshipApplyState) {
		this.internshipApplyState = internshipApplyState;
	}

	public Timestamp getChangeFillStartTime() {
		return this.changeFillStartTime;
	}

	public void setChangeFillStartTime(Timestamp changeFillStartTime) {
		this.changeFillStartTime = changeFillStartTime;
	}

	public Timestamp getChangeFillEndTime() {
		return this.changeFillEndTime;
	}

	public void setChangeFillEndTime(Timestamp changeFillEndTime) {
		this.changeFillEndTime = changeFillEndTime;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("InternshipApply (");

		sb.append(internshipApplyId);
		sb.append(", ").append(studentId);
		sb.append(", ").append(internshipReleaseId);
		sb.append(", ").append(internshipApplyState);
		sb.append(", ").append(changeFillStartTime);
		sb.append(", ").append(changeFillEndTime);

		sb.append(")");
		return sb.toString();
	}
}
