/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.isy.domain.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import top.zbeboy.isy.domain.tables.Building;
import top.zbeboy.isy.domain.tables.records.BuildingRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class BuildingDao extends DAOImpl<BuildingRecord, top.zbeboy.isy.domain.tables.pojos.Building, Integer> {

    /**
     * Create a new BuildingDao without any configuration
     */
    public BuildingDao() {
        super(Building.BUILDING, top.zbeboy.isy.domain.tables.pojos.Building.class);
    }

    /**
     * Create a new BuildingDao with an attached configuration
     */
    @Autowired
    public BuildingDao(Configuration configuration) {
        super(Building.BUILDING, top.zbeboy.isy.domain.tables.pojos.Building.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(top.zbeboy.isy.domain.tables.pojos.Building object) {
        return object.getBuildingId();
    }

    /**
     * Fetch records that have <code>building_id IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.Building> fetchByBuildingId(Integer... values) {
        return fetch(Building.BUILDING.BUILDING_ID, values);
    }

    /**
     * Fetch a unique record that has <code>building_id = value</code>
     */
    public top.zbeboy.isy.domain.tables.pojos.Building fetchOneByBuildingId(Integer value) {
        return fetchOne(Building.BUILDING.BUILDING_ID, value);
    }

    /**
     * Fetch records that have <code>building_name IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.Building> fetchByBuildingName(String... values) {
        return fetch(Building.BUILDING.BUILDING_NAME, values);
    }

    /**
     * Fetch records that have <code>building_is_del IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.Building> fetchByBuildingIsDel(Byte... values) {
        return fetch(Building.BUILDING.BUILDING_IS_DEL, values);
    }

    /**
     * Fetch records that have <code>college_id IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.Building> fetchByCollegeId(Integer... values) {
        return fetch(Building.BUILDING.COLLEGE_ID, values);
    }
}
