/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.isy.domain.tables.daos;


import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import top.zbeboy.isy.domain.tables.GraduationPracticeCompany;
import top.zbeboy.isy.domain.tables.records.GraduationPracticeCompanyRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class GraduationPracticeCompanyDao extends DAOImpl<GraduationPracticeCompanyRecord, top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany, String> {

    /**
     * Create a new GraduationPracticeCompanyDao without any configuration
     */
    public GraduationPracticeCompanyDao() {
        super(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY, top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany.class);
    }

    /**
     * Create a new GraduationPracticeCompanyDao with an attached configuration
     */
    @Autowired
    public GraduationPracticeCompanyDao(Configuration configuration) {
        super(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY, top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany object) {
        return object.getGraduationPracticeCompanyId();
    }

    /**
     * Fetch records that have <code>graduation_practice_company_id IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany> fetchByGraduationPracticeCompanyId(String... values) {
        return fetch(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY.GRADUATION_PRACTICE_COMPANY_ID, values);
    }

    /**
     * Fetch a unique record that has <code>graduation_practice_company_id = value</code>
     */
    public top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany fetchOneByGraduationPracticeCompanyId(String value) {
        return fetchOne(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY.GRADUATION_PRACTICE_COMPANY_ID, value);
    }

    /**
     * Fetch records that have <code>student_name IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany> fetchByStudentName(String... values) {
        return fetch(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY.STUDENT_NAME, values);
    }

    /**
     * Fetch records that have <code>college_class IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany> fetchByCollegeClass(String... values) {
        return fetch(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY.COLLEGE_CLASS, values);
    }

    /**
     * Fetch records that have <code>student_sex IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany> fetchByStudentSex(String... values) {
        return fetch(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY.STUDENT_SEX, values);
    }

    /**
     * Fetch records that have <code>student_number IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany> fetchByStudentNumber(String... values) {
        return fetch(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY.STUDENT_NUMBER, values);
    }

    /**
     * Fetch records that have <code>phone_number IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany> fetchByPhoneNumber(String... values) {
        return fetch(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY.PHONE_NUMBER, values);
    }

    /**
     * Fetch records that have <code>qq_mailbox IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany> fetchByQqMailbox(String... values) {
        return fetch(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY.QQ_MAILBOX, values);
    }

    /**
     * Fetch records that have <code>parental_contact IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany> fetchByParentalContact(String... values) {
        return fetch(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY.PARENTAL_CONTACT, values);
    }

    /**
     * Fetch records that have <code>headmaster IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany> fetchByHeadmaster(String... values) {
        return fetch(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY.HEADMASTER, values);
    }

    /**
     * Fetch records that have <code>headmaster_contact IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany> fetchByHeadmasterContact(String... values) {
        return fetch(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY.HEADMASTER_CONTACT, values);
    }

    /**
     * Fetch records that have <code>graduation_practice_company_name IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany> fetchByGraduationPracticeCompanyName(String... values) {
        return fetch(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY.GRADUATION_PRACTICE_COMPANY_NAME, values);
    }

    /**
     * Fetch records that have <code>graduation_practice_company_address IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany> fetchByGraduationPracticeCompanyAddress(String... values) {
        return fetch(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY.GRADUATION_PRACTICE_COMPANY_ADDRESS, values);
    }

    /**
     * Fetch records that have <code>graduation_practice_company_contacts IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany> fetchByGraduationPracticeCompanyContacts(String... values) {
        return fetch(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY.GRADUATION_PRACTICE_COMPANY_CONTACTS, values);
    }

    /**
     * Fetch records that have <code>graduation_practice_company_tel IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany> fetchByGraduationPracticeCompanyTel(String... values) {
        return fetch(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY.GRADUATION_PRACTICE_COMPANY_TEL, values);
    }

    /**
     * Fetch records that have <code>school_guidance_teacher IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany> fetchBySchoolGuidanceTeacher(String... values) {
        return fetch(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY.SCHOOL_GUIDANCE_TEACHER, values);
    }

    /**
     * Fetch records that have <code>school_guidance_teacher_tel IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany> fetchBySchoolGuidanceTeacherTel(String... values) {
        return fetch(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY.SCHOOL_GUIDANCE_TEACHER_TEL, values);
    }

    /**
     * Fetch records that have <code>start_time IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany> fetchByStartTime(Date... values) {
        return fetch(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY.START_TIME, values);
    }

    /**
     * Fetch records that have <code>end_time IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany> fetchByEndTime(Date... values) {
        return fetch(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY.END_TIME, values);
    }

    /**
     * Fetch records that have <code>commitment_book IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany> fetchByCommitmentBook(Byte... values) {
        return fetch(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY.COMMITMENT_BOOK, values);
    }

    /**
     * Fetch records that have <code>safety_responsibility_book IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany> fetchBySafetyResponsibilityBook(Byte... values) {
        return fetch(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY.SAFETY_RESPONSIBILITY_BOOK, values);
    }

    /**
     * Fetch records that have <code>practice_agreement IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany> fetchByPracticeAgreement(Byte... values) {
        return fetch(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY.PRACTICE_AGREEMENT, values);
    }

    /**
     * Fetch records that have <code>internship_application IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany> fetchByInternshipApplication(Byte... values) {
        return fetch(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY.INTERNSHIP_APPLICATION, values);
    }

    /**
     * Fetch records that have <code>practice_receiving IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany> fetchByPracticeReceiving(Byte... values) {
        return fetch(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY.PRACTICE_RECEIVING, values);
    }

    /**
     * Fetch records that have <code>security_education_agreement IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany> fetchBySecurityEducationAgreement(Byte... values) {
        return fetch(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY.SECURITY_EDUCATION_AGREEMENT, values);
    }

    /**
     * Fetch records that have <code>parental_consent IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany> fetchByParentalConsent(Byte... values) {
        return fetch(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY.PARENTAL_CONSENT, values);
    }

    /**
     * Fetch records that have <code>student_id IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany> fetchByStudentId(Integer... values) {
        return fetch(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY.STUDENT_ID, values);
    }

    /**
     * Fetch records that have <code>internship_release_id IN (values)</code>
     */
    public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeCompany> fetchByInternshipReleaseId(String... values) {
        return fetch(GraduationPracticeCompany.GRADUATION_PRACTICE_COMPANY.INTERNSHIP_RELEASE_ID, values);
    }
}
