/**
 * This class is generated by jOOQ
 */
package top.zbeboy.isy.domain.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import top.zbeboy.isy.domain.tables.GraduationPracticeUnify;
import top.zbeboy.isy.domain.tables.records.GraduationPracticeUnifyRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GraduationPracticeUnifyDao extends DAOImpl<GraduationPracticeUnifyRecord, top.zbeboy.isy.domain.tables.pojos.GraduationPracticeUnify, String> {

	/**
	 * Create a new GraduationPracticeUnifyDao without any configuration
	 */
	public GraduationPracticeUnifyDao() {
		super(GraduationPracticeUnify.GRADUATION_PRACTICE_UNIFY, top.zbeboy.isy.domain.tables.pojos.GraduationPracticeUnify.class);
	}

	/**
	 * Create a new GraduationPracticeUnifyDao with an attached configuration
	 */
	public GraduationPracticeUnifyDao(Configuration configuration) {
		super(GraduationPracticeUnify.GRADUATION_PRACTICE_UNIFY, top.zbeboy.isy.domain.tables.pojos.GraduationPracticeUnify.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected String getId(top.zbeboy.isy.domain.tables.pojos.GraduationPracticeUnify object) {
		return object.getGraduationPracticeUnifyId();
	}

	/**
	 * Fetch records that have <code>graduation_practice_unify_id IN (values)</code>
	 */
	public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeUnify> fetchByGraduationPracticeUnifyId(String... values) {
		return fetch(GraduationPracticeUnify.GRADUATION_PRACTICE_UNIFY.GRADUATION_PRACTICE_UNIFY_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>graduation_practice_unify_id = value</code>
	 */
	public top.zbeboy.isy.domain.tables.pojos.GraduationPracticeUnify fetchOneByGraduationPracticeUnifyId(String value) {
		return fetchOne(GraduationPracticeUnify.GRADUATION_PRACTICE_UNIFY.GRADUATION_PRACTICE_UNIFY_ID, value);
	}

	/**
	 * Fetch records that have <code>student_id IN (values)</code>
	 */
	public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeUnify> fetchByStudentId(Integer... values) {
		return fetch(GraduationPracticeUnify.GRADUATION_PRACTICE_UNIFY.STUDENT_ID, values);
	}

	/**
	 * Fetch records that have <code>internship_release_id IN (values)</code>
	 */
	public List<top.zbeboy.isy.domain.tables.pojos.GraduationPracticeUnify> fetchByInternshipReleaseId(String... values) {
		return fetch(GraduationPracticeUnify.GRADUATION_PRACTICE_UNIFY.INTERNSHIP_RELEASE_ID, values);
	}
}
