/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.isy.domain.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import top.zbeboy.isy.domain.Indexes;
import top.zbeboy.isy.domain.Isy;
import top.zbeboy.isy.domain.Keys;
import top.zbeboy.isy.domain.tables.records.DefenseGroupMemberRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefenseGroupMember extends TableImpl<DefenseGroupMemberRecord> {

    private static final long serialVersionUID = -396737375;

    /**
     * The reference instance of <code>isy.defense_group_member</code>
     */
    public static final DefenseGroupMember DEFENSE_GROUP_MEMBER = new DefenseGroupMember();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DefenseGroupMemberRecord> getRecordType() {
        return DefenseGroupMemberRecord.class;
    }

    /**
     * The column <code>isy.defense_group_member.graduation_design_teacher_id</code>.
     */
    public final TableField<DefenseGroupMemberRecord, String> GRADUATION_DESIGN_TEACHER_ID = createField("graduation_design_teacher_id", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>isy.defense_group_member.defense_group_id</code>.
     */
    public final TableField<DefenseGroupMemberRecord, String> DEFENSE_GROUP_ID = createField("defense_group_id", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>isy.defense_group_member.note</code>.
     */
    public final TableField<DefenseGroupMemberRecord, String> NOTE = createField("note", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * Create a <code>isy.defense_group_member</code> table reference
     */
    public DefenseGroupMember() {
        this(DSL.name("defense_group_member"), null);
    }

    /**
     * Create an aliased <code>isy.defense_group_member</code> table reference
     */
    public DefenseGroupMember(String alias) {
        this(DSL.name(alias), DEFENSE_GROUP_MEMBER);
    }

    /**
     * Create an aliased <code>isy.defense_group_member</code> table reference
     */
    public DefenseGroupMember(Name alias) {
        this(alias, DEFENSE_GROUP_MEMBER);
    }

    private DefenseGroupMember(Name alias, Table<DefenseGroupMemberRecord> aliased) {
        this(alias, aliased, null);
    }

    private DefenseGroupMember(Name alias, Table<DefenseGroupMemberRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Isy.ISY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DEFENSE_GROUP_MEMBER_DEFENSE_GROUP_ID, Indexes.DEFENSE_GROUP_MEMBER_GRADUATION_DESIGN_TEACHER_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DefenseGroupMemberRecord>> getKeys() {
        return Arrays.<UniqueKey<DefenseGroupMemberRecord>>asList(Keys.KEY_DEFENSE_GROUP_MEMBER_GRADUATION_DESIGN_TEACHER_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DefenseGroupMemberRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DefenseGroupMemberRecord, ?>>asList(Keys.DEFENSE_GROUP_MEMBER_IBFK_1, Keys.DEFENSE_GROUP_MEMBER_IBFK_2);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DefenseGroupMember as(String alias) {
        return new DefenseGroupMember(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DefenseGroupMember as(Name alias) {
        return new DefenseGroupMember(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DefenseGroupMember rename(String name) {
        return new DefenseGroupMember(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DefenseGroupMember rename(Name name) {
        return new DefenseGroupMember(name, null);
    }
}
