/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.isy.domain.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import top.zbeboy.isy.domain.Isy;
import top.zbeboy.isy.domain.Keys;
import top.zbeboy.isy.domain.tables.records.DefenseGroupRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefenseGroup extends TableImpl<DefenseGroupRecord> {

    private static final long serialVersionUID = -1663848746;

    /**
     * The reference instance of <code>isy.defense_group</code>
     */
    public static final DefenseGroup DEFENSE_GROUP = new DefenseGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DefenseGroupRecord> getRecordType() {
        return DefenseGroupRecord.class;
    }

    /**
     * The column <code>isy.defense_group.defense_group_id</code>.
     */
    public final TableField<DefenseGroupRecord, String> DEFENSE_GROUP_ID = createField("defense_group_id", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

    /**
     * The column <code>isy.defense_group.defense_group_name</code>.
     */
    public final TableField<DefenseGroupRecord, String> DEFENSE_GROUP_NAME = createField("defense_group_name", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * The column <code>isy.defense_group.schoolroom_id</code>.
     */
    public final TableField<DefenseGroupRecord, Integer> SCHOOLROOM_ID = createField("schoolroom_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>isy.defense_group.note</code>.
     */
    public final TableField<DefenseGroupRecord, String> NOTE = createField("note", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * The column <code>isy.defense_group.leader_id</code>.
     */
    public final TableField<DefenseGroupRecord, String> LEADER_ID = createField("leader_id", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>isy.defense_group.secretary_id</code>.
     */
    public final TableField<DefenseGroupRecord, String> SECRETARY_ID = createField("secretary_id", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>isy.defense_group.defense_arrangement_id</code>.
     */
    public final TableField<DefenseGroupRecord, String> DEFENSE_ARRANGEMENT_ID = createField("defense_arrangement_id", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

    /**
     * The column <code>isy.defense_group.create_time</code>.
     */
    public final TableField<DefenseGroupRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>isy.defense_group</code> table reference
     */
    public DefenseGroup() {
        this("defense_group", null);
    }

    /**
     * Create an aliased <code>isy.defense_group</code> table reference
     */
    public DefenseGroup(String alias) {
        this(alias, DEFENSE_GROUP);
    }

    private DefenseGroup(String alias, Table<DefenseGroupRecord> aliased) {
        this(alias, aliased, null);
    }

    private DefenseGroup(String alias, Table<DefenseGroupRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Isy.ISY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DefenseGroupRecord> getPrimaryKey() {
        return Keys.KEY_DEFENSE_GROUP_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DefenseGroupRecord>> getKeys() {
        return Arrays.<UniqueKey<DefenseGroupRecord>>asList(Keys.KEY_DEFENSE_GROUP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DefenseGroupRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DefenseGroupRecord, ?>>asList(Keys.DEFENSE_GROUP_IBFK_1, Keys.DEFENSE_GROUP_IBFK_2);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DefenseGroup as(String alias) {
        return new DefenseGroup(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DefenseGroup rename(String name) {
        return new DefenseGroup(name, null);
    }
}
