/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.isy.domain.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import top.zbeboy.isy.domain.Isy;
import top.zbeboy.isy.domain.Keys;
import top.zbeboy.isy.domain.tables.records.GraduationDesignArchivesRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GraduationDesignArchives extends TableImpl<GraduationDesignArchivesRecord> {

    private static final long serialVersionUID = -1247898315;

    /**
     * The reference instance of <code>isy.graduation_design_archives</code>
     */
    public static final GraduationDesignArchives GRADUATION_DESIGN_ARCHIVES = new GraduationDesignArchives();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GraduationDesignArchivesRecord> getRecordType() {
        return GraduationDesignArchivesRecord.class;
    }

    /**
     * The column <code>isy.graduation_design_archives.graduation_design_presubject_id</code>.
     */
    public final TableField<GraduationDesignArchivesRecord, String> GRADUATION_DESIGN_PRESUBJECT_ID = createField("graduation_design_presubject_id", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

    /**
     * The column <code>isy.graduation_design_archives.is_excellent</code>.
     */
    public final TableField<GraduationDesignArchivesRecord, Byte> IS_EXCELLENT = createField("is_excellent", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>isy.graduation_design_archives.archive_number</code>.
     */
    public final TableField<GraduationDesignArchivesRecord, String> ARCHIVE_NUMBER = createField("archive_number", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * The column <code>isy.graduation_design_archives.note</code>.
     */
    public final TableField<GraduationDesignArchivesRecord, String> NOTE = createField("note", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * Create a <code>isy.graduation_design_archives</code> table reference
     */
    public GraduationDesignArchives() {
        this("graduation_design_archives", null);
    }

    /**
     * Create an aliased <code>isy.graduation_design_archives</code> table reference
     */
    public GraduationDesignArchives(String alias) {
        this(alias, GRADUATION_DESIGN_ARCHIVES);
    }

    private GraduationDesignArchives(String alias, Table<GraduationDesignArchivesRecord> aliased) {
        this(alias, aliased, null);
    }

    private GraduationDesignArchives(String alias, Table<GraduationDesignArchivesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Isy.ISY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GraduationDesignArchivesRecord>> getKeys() {
        return Arrays.<UniqueKey<GraduationDesignArchivesRecord>>asList(Keys.KEY_GRADUATION_DESIGN_ARCHIVES_GRADUATION_DESIGN_PRESUBJECT_ID, Keys.KEY_GRADUATION_DESIGN_ARCHIVES_ARCHIVE_NUMBER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<GraduationDesignArchivesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<GraduationDesignArchivesRecord, ?>>asList(Keys.GRADUATION_DESIGN_ARCHIVES_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraduationDesignArchives as(String alias) {
        return new GraduationDesignArchives(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GraduationDesignArchives rename(String name) {
        return new GraduationDesignArchives(name, null);
    }
}
