/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.isy.domain.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import top.zbeboy.isy.domain.Isy;
import top.zbeboy.isy.domain.Keys;
import top.zbeboy.isy.domain.tables.records.GraduateBillRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GraduateBill extends TableImpl<GraduateBillRecord> {

    private static final long serialVersionUID = -1544787839;

    /**
     * The reference instance of <code>isy.graduate_bill</code>
     */
    public static final GraduateBill GRADUATE_BILL = new GraduateBill();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GraduateBillRecord> getRecordType() {
        return GraduateBillRecord.class;
    }

    /**
     * The column <code>isy.graduate_bill.graduate_bill_id</code>.
     */
    public final TableField<GraduateBillRecord, String> GRADUATE_BILL_ID = createField("graduate_bill_id", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

    /**
     * The column <code>isy.graduate_bill.graduation_design_release_id</code>.
     */
    public final TableField<GraduateBillRecord, String> GRADUATION_DESIGN_RELEASE_ID = createField("graduation_design_release_id", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

    /**
     * The column <code>isy.graduate_bill.graduation_design_presubject_id</code>.
     */
    public final TableField<GraduateBillRecord, String> GRADUATION_DESIGN_PRESUBJECT_ID = createField("graduation_design_presubject_id", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

    /**
     * Create a <code>isy.graduate_bill</code> table reference
     */
    public GraduateBill() {
        this("graduate_bill", null);
    }

    /**
     * Create an aliased <code>isy.graduate_bill</code> table reference
     */
    public GraduateBill(String alias) {
        this(alias, GRADUATE_BILL);
    }

    private GraduateBill(String alias, Table<GraduateBillRecord> aliased) {
        this(alias, aliased, null);
    }

    private GraduateBill(String alias, Table<GraduateBillRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Isy.ISY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GraduateBillRecord> getPrimaryKey() {
        return Keys.KEY_GRADUATE_BILL_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GraduateBillRecord>> getKeys() {
        return Arrays.<UniqueKey<GraduateBillRecord>>asList(Keys.KEY_GRADUATE_BILL_PRIMARY, Keys.KEY_GRADUATE_BILL_GRADUATION_DESIGN_PRESUBJECT_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<GraduateBillRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<GraduateBillRecord, ?>>asList(Keys.GRADUATE_BILL_IBFK_1, Keys.GRADUATE_BILL_IBFK_2);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraduateBill as(String alias) {
        return new GraduateBill(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GraduateBill rename(String name) {
        return new GraduateBill(name, null);
    }
}
