/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.isy.domain.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import top.zbeboy.isy.domain.Indexes;
import top.zbeboy.isy.domain.Isy;
import top.zbeboy.isy.domain.Keys;
import top.zbeboy.isy.domain.tables.records.GraduationDesignPlanRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GraduationDesignPlan extends TableImpl<GraduationDesignPlanRecord> {

    private static final long serialVersionUID = -267414147;

    /**
     * The reference instance of <code>isy.graduation_design_plan</code>
     */
    public static final GraduationDesignPlan GRADUATION_DESIGN_PLAN = new GraduationDesignPlan();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GraduationDesignPlanRecord> getRecordType() {
        return GraduationDesignPlanRecord.class;
    }

    /**
     * The column <code>isy.graduation_design_plan.graduation_design_plan_id</code>.
     */
    public final TableField<GraduationDesignPlanRecord, String> GRADUATION_DESIGN_PLAN_ID = createField("graduation_design_plan_id", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>isy.graduation_design_plan.scheduling</code>.
     */
    public final TableField<GraduationDesignPlanRecord, String> SCHEDULING = createField("scheduling", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>isy.graduation_design_plan.supervision_time</code>.
     */
    public final TableField<GraduationDesignPlanRecord, String> SUPERVISION_TIME = createField("supervision_time", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>isy.graduation_design_plan.guide_content</code>.
     */
    public final TableField<GraduationDesignPlanRecord, String> GUIDE_CONTENT = createField("guide_content", org.jooq.impl.SQLDataType.VARCHAR(150).nullable(false), this, "");

    /**
     * The column <code>isy.graduation_design_plan.note</code>.
     */
    public final TableField<GraduationDesignPlanRecord, String> NOTE = createField("note", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>isy.graduation_design_plan.add_time</code>.
     */
    public final TableField<GraduationDesignPlanRecord, Timestamp> ADD_TIME = createField("add_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>isy.graduation_design_plan.graduation_design_teacher_id</code>.
     */
    public final TableField<GraduationDesignPlanRecord, String> GRADUATION_DESIGN_TEACHER_ID = createField("graduation_design_teacher_id", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>isy.graduation_design_plan.schoolroom_id</code>.
     */
    public final TableField<GraduationDesignPlanRecord, Integer> SCHOOLROOM_ID = createField("schoolroom_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>isy.graduation_design_plan</code> table reference
     */
    public GraduationDesignPlan() {
        this(DSL.name("graduation_design_plan"), null);
    }

    /**
     * Create an aliased <code>isy.graduation_design_plan</code> table reference
     */
    public GraduationDesignPlan(String alias) {
        this(DSL.name(alias), GRADUATION_DESIGN_PLAN);
    }

    /**
     * Create an aliased <code>isy.graduation_design_plan</code> table reference
     */
    public GraduationDesignPlan(Name alias) {
        this(alias, GRADUATION_DESIGN_PLAN);
    }

    private GraduationDesignPlan(Name alias, Table<GraduationDesignPlanRecord> aliased) {
        this(alias, aliased, null);
    }

    private GraduationDesignPlan(Name alias, Table<GraduationDesignPlanRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Isy.ISY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.GRADUATION_DESIGN_PLAN_GRADUATION_DESIGN_TEACHER_ID, Indexes.GRADUATION_DESIGN_PLAN_PRIMARY, Indexes.GRADUATION_DESIGN_PLAN_SCHOOLROOM_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GraduationDesignPlanRecord> getPrimaryKey() {
        return Keys.KEY_GRADUATION_DESIGN_PLAN_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GraduationDesignPlanRecord>> getKeys() {
        return Arrays.<UniqueKey<GraduationDesignPlanRecord>>asList(Keys.KEY_GRADUATION_DESIGN_PLAN_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<GraduationDesignPlanRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<GraduationDesignPlanRecord, ?>>asList(Keys.GRADUATION_DESIGN_PLAN_IBFK_1, Keys.GRADUATION_DESIGN_PLAN_IBFK_2);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraduationDesignPlan as(String alias) {
        return new GraduationDesignPlan(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraduationDesignPlan as(Name alias) {
        return new GraduationDesignPlan(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GraduationDesignPlan rename(String name) {
        return new GraduationDesignPlan(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GraduationDesignPlan rename(Name name) {
        return new GraduationDesignPlan(name, null);
    }
}
