/**
 * This class is generated by jOOQ
 */
package top.zbeboy.isy.domain.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import top.zbeboy.isy.domain.Isy;
import top.zbeboy.isy.domain.Keys;
import top.zbeboy.isy.domain.tables.records.InternshipCompanyHistoryRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InternshipCompanyHistory extends TableImpl<InternshipCompanyHistoryRecord> {

	private static final long serialVersionUID = 359504685;

	/**
	 * The reference instance of <code>isy.internship_company_history</code>
	 */
	public static final InternshipCompanyHistory INTERNSHIP_COMPANY_HISTORY = new InternshipCompanyHistory();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<InternshipCompanyHistoryRecord> getRecordType() {
		return InternshipCompanyHistoryRecord.class;
	}

	/**
	 * The column <code>isy.internship_company_history.internship_company_history_id</code>.
	 */
	public final TableField<InternshipCompanyHistoryRecord, Integer> INTERNSHIP_COMPANY_HISTORY_ID = createField("internship_company_history_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>isy.internship_company_history.internship_company_name</code>.
	 */
	public final TableField<InternshipCompanyHistoryRecord, String> INTERNSHIP_COMPANY_NAME = createField("internship_company_name", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false), this, "");

	/**
	 * The column <code>isy.internship_company_history.internship_company_address</code>.
	 */
	public final TableField<InternshipCompanyHistoryRecord, String> INTERNSHIP_COMPANY_ADDRESS = createField("internship_company_address", org.jooq.impl.SQLDataType.VARCHAR.length(500).nullable(false), this, "");

	/**
	 * The column <code>isy.internship_company_history.internship_company_contacts</code>.
	 */
	public final TableField<InternshipCompanyHistoryRecord, String> INTERNSHIP_COMPANY_CONTACTS = createField("internship_company_contacts", org.jooq.impl.SQLDataType.VARCHAR.length(10).nullable(false), this, "");

	/**
	 * The column <code>isy.internship_company_history.internship_company_tel</code>.
	 */
	public final TableField<InternshipCompanyHistoryRecord, String> INTERNSHIP_COMPANY_TEL = createField("internship_company_tel", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>isy.internship_company_history.student_id</code>.
	 */
	public final TableField<InternshipCompanyHistoryRecord, Integer> STUDENT_ID = createField("student_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>isy.internship_company_history.internship_release_id</code>.
	 */
	public final TableField<InternshipCompanyHistoryRecord, String> INTERNSHIP_RELEASE_ID = createField("internship_release_id", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * Create a <code>isy.internship_company_history</code> table reference
	 */
	public InternshipCompanyHistory() {
		this("internship_company_history", null);
	}

	/**
	 * Create an aliased <code>isy.internship_company_history</code> table reference
	 */
	public InternshipCompanyHistory(String alias) {
		this(alias, INTERNSHIP_COMPANY_HISTORY);
	}

	private InternshipCompanyHistory(String alias, Table<InternshipCompanyHistoryRecord> aliased) {
		this(alias, aliased, null);
	}

	private InternshipCompanyHistory(String alias, Table<InternshipCompanyHistoryRecord> aliased, Field<?>[] parameters) {
		super(alias, Isy.ISY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<InternshipCompanyHistoryRecord, Integer> getIdentity() {
		return Keys.IDENTITY_INTERNSHIP_COMPANY_HISTORY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<InternshipCompanyHistoryRecord> getPrimaryKey() {
		return Keys.KEY_INTERNSHIP_COMPANY_HISTORY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<InternshipCompanyHistoryRecord>> getKeys() {
		return Arrays.<UniqueKey<InternshipCompanyHistoryRecord>>asList(Keys.KEY_INTERNSHIP_COMPANY_HISTORY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<InternshipCompanyHistoryRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<InternshipCompanyHistoryRecord, ?>>asList(Keys.INTERNSHIP_COMPANY_HISTORY_IBFK_1, Keys.INTERNSHIP_COMPANY_HISTORY_IBFK_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InternshipCompanyHistory as(String alias) {
		return new InternshipCompanyHistory(alias, this);
	}

	/**
	 * Rename this table
	 */
	public InternshipCompanyHistory rename(String name) {
		return new InternshipCompanyHistory(name, null);
	}
}
