/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.isy.domain.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import top.zbeboy.isy.domain.Isy;
import top.zbeboy.isy.domain.Keys;
import top.zbeboy.isy.domain.tables.records.RoleApplicationRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleApplication extends TableImpl<RoleApplicationRecord> {

    private static final long serialVersionUID = -391068051;

    /**
     * The reference instance of <code>isy.role_application</code>
     */
    public static final RoleApplication ROLE_APPLICATION = new RoleApplication();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoleApplicationRecord> getRecordType() {
        return RoleApplicationRecord.class;
    }

    /**
     * The column <code>isy.role_application.role_id</code>.
     */
    public final TableField<RoleApplicationRecord, Integer> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>isy.role_application.application_id</code>.
     */
    public final TableField<RoleApplicationRecord, Integer> APPLICATION_ID = createField("application_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>isy.role_application</code> table reference
     */
    public RoleApplication() {
        this("role_application", null);
    }

    /**
     * Create an aliased <code>isy.role_application</code> table reference
     */
    public RoleApplication(String alias) {
        this(alias, ROLE_APPLICATION);
    }

    private RoleApplication(String alias, Table<RoleApplicationRecord> aliased) {
        this(alias, aliased, null);
    }

    private RoleApplication(String alias, Table<RoleApplicationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Isy.ISY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RoleApplicationRecord> getPrimaryKey() {
        return Keys.KEY_ROLE_APPLICATION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RoleApplicationRecord>> getKeys() {
        return Arrays.<UniqueKey<RoleApplicationRecord>>asList(Keys.KEY_ROLE_APPLICATION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RoleApplicationRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RoleApplicationRecord, ?>>asList(Keys.ROLE_APPLICATION_IBFK_1, Keys.ROLE_APPLICATION_IBFK_2);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoleApplication as(String alias) {
        return new RoleApplication(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RoleApplication rename(String name) {
        return new RoleApplication(name, null);
    }
}
