/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.isy.domain.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import top.zbeboy.isy.domain.Isy;
import top.zbeboy.isy.domain.Keys;
import top.zbeboy.isy.domain.tables.records.SyncElasticRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SyncElastic extends TableImpl<SyncElasticRecord> {

    private static final long serialVersionUID = -1903202404;

    /**
     * The reference instance of <code>isy.sync_elastic</code>
     */
    public static final SyncElastic SYNC_ELASTIC = new SyncElastic();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SyncElasticRecord> getRecordType() {
        return SyncElasticRecord.class;
    }

    /**
     * The column <code>isy.sync_elastic.sync_elastic</code>.
     */
    public final TableField<SyncElasticRecord, Integer> SYNC_ELASTIC_ = createField("sync_elastic", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>isy.sync_elastic.application_name</code>.
     */
    public final TableField<SyncElasticRecord, String> APPLICATION_NAME = createField("application_name", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

    /**
     * The column <code>isy.sync_elastic.sync_time</code>.
     */
    public final TableField<SyncElasticRecord, Timestamp> SYNC_TIME = createField("sync_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>isy.sync_elastic.sync_url</code>.
     */
    public final TableField<SyncElasticRecord, String> SYNC_URL = createField("sync_url", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false), this, "");

    /**
     * The column <code>isy.sync_elastic.username</code>.
     */
    public final TableField<SyncElasticRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

    /**
     * Create a <code>isy.sync_elastic</code> table reference
     */
    public SyncElastic() {
        this("sync_elastic", null);
    }

    /**
     * Create an aliased <code>isy.sync_elastic</code> table reference
     */
    public SyncElastic(String alias) {
        this(alias, SYNC_ELASTIC);
    }

    private SyncElastic(String alias, Table<SyncElasticRecord> aliased) {
        this(alias, aliased, null);
    }

    private SyncElastic(String alias, Table<SyncElasticRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Isy.ISY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SyncElasticRecord, Integer> getIdentity() {
        return Keys.IDENTITY_SYNC_ELASTIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SyncElasticRecord> getPrimaryKey() {
        return Keys.KEY_SYNC_ELASTIC_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SyncElasticRecord>> getKeys() {
        return Arrays.<UniqueKey<SyncElasticRecord>>asList(Keys.KEY_SYNC_ELASTIC_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<SyncElasticRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SyncElasticRecord, ?>>asList(Keys.SYNC_ELASTIC_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SyncElastic as(String alias) {
        return new SyncElastic(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SyncElastic rename(String name) {
        return new SyncElastic(name, null);
    }
}
