/**
 * This class is generated by jOOQ
 */
package top.zbeboy.isy.domain.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import top.zbeboy.isy.domain.Isy;
import top.zbeboy.isy.domain.Keys;
import top.zbeboy.isy.domain.tables.records.SystemMailboxRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemMailbox extends TableImpl<SystemMailboxRecord> {

	private static final long serialVersionUID = 599464665;

	/**
	 * The reference instance of <code>isy.system_mailbox</code>
	 */
	public static final SystemMailbox SYSTEM_MAILBOX = new SystemMailbox();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SystemMailboxRecord> getRecordType() {
		return SystemMailboxRecord.class;
	}

	/**
	 * The column <code>isy.system_mailbox.system_mailbox_id</code>.
	 */
	public final TableField<SystemMailboxRecord, String> SYSTEM_MAILBOX_ID = createField("system_mailbox_id", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>isy.system_mailbox.send_time</code>.
	 */
	public final TableField<SystemMailboxRecord, Timestamp> SEND_TIME = createField("send_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>isy.system_mailbox.accept_mail</code>.
	 */
	public final TableField<SystemMailboxRecord, String> ACCEPT_MAIL = createField("accept_mail", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * Create a <code>isy.system_mailbox</code> table reference
	 */
	public SystemMailbox() {
		this("system_mailbox", null);
	}

	/**
	 * Create an aliased <code>isy.system_mailbox</code> table reference
	 */
	public SystemMailbox(String alias) {
		this(alias, SYSTEM_MAILBOX);
	}

	private SystemMailbox(String alias, Table<SystemMailboxRecord> aliased) {
		this(alias, aliased, null);
	}

	private SystemMailbox(String alias, Table<SystemMailboxRecord> aliased, Field<?>[] parameters) {
		super(alias, Isy.ISY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<SystemMailboxRecord> getPrimaryKey() {
		return Keys.KEY_SYSTEM_MAILBOX_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<SystemMailboxRecord>> getKeys() {
		return Arrays.<UniqueKey<SystemMailboxRecord>>asList(Keys.KEY_SYSTEM_MAILBOX_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SystemMailbox as(String alias) {
		return new SystemMailbox(alias, this);
	}

	/**
	 * Rename this table
	 */
	public SystemMailbox rename(String name) {
		return new SystemMailbox(name, null);
	}
}
