/**
 * This class is generated by jOOQ
 */
package top.zbeboy.isy.domain.tables.records;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import top.zbeboy.isy.domain.tables.ApplicationType;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApplicationTypeRecord extends UpdatableRecordImpl<ApplicationTypeRecord> implements Record2<Integer, String> {

	private static final long serialVersionUID = -460056714;

	/**
	 * Setter for <code>isy.application_type.application_type_id</code>.
	 */
	public void setApplicationTypeId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>isy.application_type.application_type_id</code>.
	 */
	@NotNull
	public Integer getApplicationTypeId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>isy.application_type.application_type_name</code>.
	 */
	public void setApplicationTypeName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>isy.application_type.application_type_name</code>.
	 */
	@NotNull
	@Size(max = 32)
	public String getApplicationTypeName() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return ApplicationType.APPLICATION_TYPE.APPLICATION_TYPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return ApplicationType.APPLICATION_TYPE.APPLICATION_TYPE_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getApplicationTypeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getApplicationTypeName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ApplicationTypeRecord value1(Integer value) {
		setApplicationTypeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ApplicationTypeRecord value2(String value) {
		setApplicationTypeName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ApplicationTypeRecord values(Integer value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ApplicationTypeRecord
	 */
	public ApplicationTypeRecord() {
		super(ApplicationType.APPLICATION_TYPE);
	}

	/**
	 * Create a detached, initialised ApplicationTypeRecord
	 */
	public ApplicationTypeRecord(Integer applicationTypeId, String applicationTypeName) {
		super(ApplicationType.APPLICATION_TYPE);

		setValue(0, applicationTypeId);
		setValue(1, applicationTypeName);
	}
}
