/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.isy.domain.tables.records;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import top.zbeboy.isy.domain.tables.DefenseGroupMember;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefenseGroupMemberRecord extends UpdatableRecordImpl<DefenseGroupMemberRecord> implements Record4<String, Integer, String, String> {

    private static final long serialVersionUID = -1025091565;

    /**
     * Setter for <code>isy.defense_group_member.group_member_id</code>.
     */
    public void setGroupMemberId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>isy.defense_group_member.group_member_id</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getGroupMemberId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>isy.defense_group_member.staff_id</code>.
     */
    public void setStaffId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>isy.defense_group_member.staff_id</code>.
     */
    @NotNull
    public Integer getStaffId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>isy.defense_group_member.defense_group_id</code>.
     */
    public void setDefenseGroupId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>isy.defense_group_member.defense_group_id</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getDefenseGroupId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>isy.defense_group_member.note</code>.
     */
    public void setNote(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>isy.defense_group_member.note</code>.
     */
    @Size(max = 100)
    public String getNote() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, Integer, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, Integer, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return DefenseGroupMember.DEFENSE_GROUP_MEMBER.GROUP_MEMBER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return DefenseGroupMember.DEFENSE_GROUP_MEMBER.STAFF_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return DefenseGroupMember.DEFENSE_GROUP_MEMBER.DEFENSE_GROUP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return DefenseGroupMember.DEFENSE_GROUP_MEMBER.NOTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getGroupMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getStaffId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDefenseGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DefenseGroupMemberRecord value1(String value) {
        setGroupMemberId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DefenseGroupMemberRecord value2(Integer value) {
        setStaffId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DefenseGroupMemberRecord value3(String value) {
        setDefenseGroupId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DefenseGroupMemberRecord value4(String value) {
        setNote(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DefenseGroupMemberRecord values(String value1, Integer value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DefenseGroupMemberRecord
     */
    public DefenseGroupMemberRecord() {
        super(DefenseGroupMember.DEFENSE_GROUP_MEMBER);
    }

    /**
     * Create a detached, initialised DefenseGroupMemberRecord
     */
    public DefenseGroupMemberRecord(String groupMemberId, Integer staffId, String defenseGroupId, String note) {
        super(DefenseGroupMember.DEFENSE_GROUP_MEMBER);

        set(0, groupMemberId);
        set(1, staffId);
        set(2, defenseGroupId);
        set(3, note);
    }
}
