/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.isy.domain.tables.records;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;

import top.zbeboy.isy.domain.tables.DefenseRate;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefenseRateRecord extends TableRecordImpl<DefenseRateRecord> implements Record3<String, String, Double> {

    private static final long serialVersionUID = 1699716906;

    /**
     * Setter for <code>isy.defense_rate.defense_order_id</code>.
     */
    public void setDefenseOrderId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>isy.defense_rate.defense_order_id</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getDefenseOrderId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>isy.defense_rate.graduation_design_teacher_id</code>.
     */
    public void setGraduationDesignTeacherId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>isy.defense_rate.graduation_design_teacher_id</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getGraduationDesignTeacherId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>isy.defense_rate.grade</code>.
     */
    public void setGrade(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>isy.defense_rate.grade</code>.
     */
    @NotNull
    public Double getGrade() {
        return (Double) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, Double> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, Double> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return DefenseRate.DEFENSE_RATE.DEFENSE_ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DefenseRate.DEFENSE_RATE.GRADUATION_DESIGN_TEACHER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return DefenseRate.DEFENSE_RATE.GRADE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getDefenseOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getGraduationDesignTeacherId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getGrade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DefenseRateRecord value1(String value) {
        setDefenseOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DefenseRateRecord value2(String value) {
        setGraduationDesignTeacherId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DefenseRateRecord value3(Double value) {
        setGrade(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DefenseRateRecord values(String value1, String value2, Double value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DefenseRateRecord
     */
    public DefenseRateRecord() {
        super(DefenseRate.DEFENSE_RATE);
    }

    /**
     * Create a detached, initialised DefenseRateRecord
     */
    public DefenseRateRecord(String defenseOrderId, String graduationDesignTeacherId, Double grade) {
        super(DefenseRate.DEFENSE_RATE);

        set(0, defenseOrderId);
        set(1, graduationDesignTeacherId);
        set(2, grade);
    }
}
