/**
 * This class is generated by jOOQ
 */
package top.zbeboy.isy.domain.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import top.zbeboy.isy.domain.tables.InternshipApply;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InternshipApplyRecord extends UpdatableRecordImpl<InternshipApplyRecord> implements Record8<String, Integer, String, Integer, String, Timestamp, Timestamp, Timestamp> {

	private static final long serialVersionUID = -850891322;

	/**
	 * Setter for <code>isy.internship_apply.internship_apply_id</code>.
	 */
	public void setInternshipApplyId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>isy.internship_apply.internship_apply_id</code>.
	 */
	@NotNull
	@Size(max = 64)
	public String getInternshipApplyId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>isy.internship_apply.student_id</code>.
	 */
	public void setStudentId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>isy.internship_apply.student_id</code>.
	 */
	@NotNull
	public Integer getStudentId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>isy.internship_apply.internship_release_id</code>.
	 */
	public void setInternshipReleaseId(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>isy.internship_apply.internship_release_id</code>.
	 */
	@NotNull
	@Size(max = 64)
	public String getInternshipReleaseId() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>isy.internship_apply.internship_apply_state</code>.
	 */
	public void setInternshipApplyState(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>isy.internship_apply.internship_apply_state</code>.
	 */
	public Integer getInternshipApplyState() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>isy.internship_apply.reason</code>.
	 */
	public void setReason(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>isy.internship_apply.reason</code>.
	 */
	@Size(max = 500)
	public String getReason() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>isy.internship_apply.change_fill_start_time</code>.
	 */
	public void setChangeFillStartTime(Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>isy.internship_apply.change_fill_start_time</code>.
	 */
	public Timestamp getChangeFillStartTime() {
		return (Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>isy.internship_apply.change_fill_end_time</code>.
	 */
	public void setChangeFillEndTime(Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>isy.internship_apply.change_fill_end_time</code>.
	 */
	public Timestamp getChangeFillEndTime() {
		return (Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>isy.internship_apply.apply_time</code>.
	 */
	public void setApplyTime(Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>isy.internship_apply.apply_time</code>.
	 */
	@NotNull
	public Timestamp getApplyTime() {
		return (Timestamp) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<String, Integer, String, Integer, String, Timestamp, Timestamp, Timestamp> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<String, Integer, String, Integer, String, Timestamp, Timestamp, Timestamp> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return InternshipApply.INTERNSHIP_APPLY.INTERNSHIP_APPLY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return InternshipApply.INTERNSHIP_APPLY.STUDENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return InternshipApply.INTERNSHIP_APPLY.INTERNSHIP_RELEASE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return InternshipApply.INTERNSHIP_APPLY.INTERNSHIP_APPLY_STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return InternshipApply.INTERNSHIP_APPLY.REASON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field6() {
		return InternshipApply.INTERNSHIP_APPLY.CHANGE_FILL_START_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field7() {
		return InternshipApply.INTERNSHIP_APPLY.CHANGE_FILL_END_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field8() {
		return InternshipApply.INTERNSHIP_APPLY.APPLY_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getInternshipApplyId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getStudentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getInternshipReleaseId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getInternshipApplyState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getReason();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value6() {
		return getChangeFillStartTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value7() {
		return getChangeFillEndTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value8() {
		return getApplyTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InternshipApplyRecord value1(String value) {
		setInternshipApplyId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InternshipApplyRecord value2(Integer value) {
		setStudentId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InternshipApplyRecord value3(String value) {
		setInternshipReleaseId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InternshipApplyRecord value4(Integer value) {
		setInternshipApplyState(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InternshipApplyRecord value5(String value) {
		setReason(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InternshipApplyRecord value6(Timestamp value) {
		setChangeFillStartTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InternshipApplyRecord value7(Timestamp value) {
		setChangeFillEndTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InternshipApplyRecord value8(Timestamp value) {
		setApplyTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InternshipApplyRecord values(String value1, Integer value2, String value3, Integer value4, String value5, Timestamp value6, Timestamp value7, Timestamp value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached InternshipApplyRecord
	 */
	public InternshipApplyRecord() {
		super(InternshipApply.INTERNSHIP_APPLY);
	}

	/**
	 * Create a detached, initialised InternshipApplyRecord
	 */
	public InternshipApplyRecord(String internshipApplyId, Integer studentId, String internshipReleaseId, Integer internshipApplyState, String reason, Timestamp changeFillStartTime, Timestamp changeFillEndTime, Timestamp applyTime) {
		super(InternshipApply.INTERNSHIP_APPLY);

		setValue(0, internshipApplyId);
		setValue(1, studentId);
		setValue(2, internshipReleaseId);
		setValue(3, internshipApplyState);
		setValue(4, reason);
		setValue(5, changeFillStartTime);
		setValue(6, changeFillEndTime);
		setValue(7, applyTime);
	}
}
