/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.isy.domain.tables.records;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import top.zbeboy.isy.domain.tables.RoleApplication;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleApplicationRecord extends UpdatableRecordImpl<RoleApplicationRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 2108793375;

    /**
     * Setter for <code>isy.role_application.role_id</code>.
     */
    public void setRoleId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>isy.role_application.role_id</code>.
     */
    @NotNull
    public Integer getRoleId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>isy.role_application.application_id</code>.
     */
    public void setApplicationId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>isy.role_application.application_id</code>.
     */
    @NotNull
    public Integer getApplicationId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RoleApplication.ROLE_APPLICATION.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return RoleApplication.ROLE_APPLICATION.APPLICATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getApplicationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoleApplicationRecord value1(Integer value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoleApplicationRecord value2(Integer value) {
        setApplicationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoleApplicationRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoleApplicationRecord
     */
    public RoleApplicationRecord() {
        super(RoleApplication.ROLE_APPLICATION);
    }

    /**
     * Create a detached, initialised RoleApplicationRecord
     */
    public RoleApplicationRecord(Integer roleId, Integer applicationId) {
        super(RoleApplication.ROLE_APPLICATION);

        set(0, roleId);
        set(1, applicationId);
    }
}
