/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.isy.domain.tables.records;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;

import top.zbeboy.isy.domain.tables.Staff;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StaffRecord extends UpdatableRecordImpl<StaffRecord> implements Record11<Integer, String, String, String, String, Integer, Integer, String, Integer, Integer, String> {

    private static final long serialVersionUID = -922147984;

    /**
     * Setter for <code>isy.staff.staff_id</code>.
     */
    public void setStaffId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>isy.staff.staff_id</code>.
     */
    public Integer getStaffId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>isy.staff.staff_number</code>.
     */
    public void setStaffNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>isy.staff.staff_number</code>.
     */
    @NotNull
    @Size(max = 20)
    public String getStaffNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>isy.staff.birthday</code>.
     */
    public void setBirthday(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>isy.staff.birthday</code>.
     */
    @Size(max = 48)
    public String getBirthday() {
        return (String) get(2);
    }

    /**
     * Setter for <code>isy.staff.sex</code>.
     */
    public void setSex(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>isy.staff.sex</code>.
     */
    @Size(max = 24)
    public String getSex() {
        return (String) get(3);
    }

    /**
     * Setter for <code>isy.staff.family_residence</code>.
     */
    public void setFamilyResidence(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>isy.staff.family_residence</code>.
     */
    @Size(max = 192)
    public String getFamilyResidence() {
        return (String) get(4);
    }

    /**
     * Setter for <code>isy.staff.political_landscape_id</code>.
     */
    public void setPoliticalLandscapeId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>isy.staff.political_landscape_id</code>.
     */
    public Integer getPoliticalLandscapeId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>isy.staff.nation_id</code>.
     */
    public void setNationId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>isy.staff.nation_id</code>.
     */
    public Integer getNationId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>isy.staff.post</code>.
     */
    public void setPost(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>isy.staff.post</code>.
     */
    @Size(max = 500)
    public String getPost() {
        return (String) get(7);
    }

    /**
     * Setter for <code>isy.staff.academic_title_id</code>.
     */
    public void setAcademicTitleId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>isy.staff.academic_title_id</code>.
     */
    public Integer getAcademicTitleId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>isy.staff.department_id</code>.
     */
    public void setDepartmentId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>isy.staff.department_id</code>.
     */
    @NotNull
    public Integer getDepartmentId() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>isy.staff.username</code>.
     */
    public void setUsername(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>isy.staff.username</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getUsername() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, String, String, String, Integer, Integer, String, Integer, Integer, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, String, String, String, Integer, Integer, String, Integer, Integer, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Staff.STAFF.STAFF_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Staff.STAFF.STAFF_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Staff.STAFF.BIRTHDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Staff.STAFF.SEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Staff.STAFF.FAMILY_RESIDENCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Staff.STAFF.POLITICAL_LANDSCAPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Staff.STAFF.NATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Staff.STAFF.POST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Staff.STAFF.ACADEMIC_TITLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Staff.STAFF.DEPARTMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Staff.STAFF.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getStaffId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getStaffNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getFamilyResidence();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getPoliticalLandscapeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getNationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getPost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getAcademicTitleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getDepartmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getStaffId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getStaffNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getFamilyResidence();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getPoliticalLandscapeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getNationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getPost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getAcademicTitleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getDepartmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value1(Integer value) {
        setStaffId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value2(String value) {
        setStaffNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value3(String value) {
        setBirthday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value4(String value) {
        setSex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value5(String value) {
        setFamilyResidence(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value6(Integer value) {
        setPoliticalLandscapeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value7(Integer value) {
        setNationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value8(String value) {
        setPost(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value9(Integer value) {
        setAcademicTitleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value10(Integer value) {
        setDepartmentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value11(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord values(Integer value1, String value2, String value3, String value4, String value5, Integer value6, Integer value7, String value8, Integer value9, Integer value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StaffRecord
     */
    public StaffRecord() {
        super(Staff.STAFF);
    }

    /**
     * Create a detached, initialised StaffRecord
     */
    public StaffRecord(Integer staffId, String staffNumber, String birthday, String sex, String familyResidence, Integer politicalLandscapeId, Integer nationId, String post, Integer academicTitleId, Integer departmentId, String username) {
        super(Staff.STAFF);

        set(0, staffId);
        set(1, staffNumber);
        set(2, birthday);
        set(3, sex);
        set(4, familyResidence);
        set(5, politicalLandscapeId);
        set(6, nationId);
        set(7, post);
        set(8, academicTitleId);
        set(9, departmentId);
        set(10, username);
    }
}
